mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


app_name = 'myauth'

urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True,
         ),
         name='login'
    ),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
]

mysite/requestdataapp/urls.py
from django.urls import path
from .views import process_get_view, user_form, handle_file_upload

app_name = 'requestdataapp'

urlpatterns = [
    path('get/', process_get_view, name='get-vew'),
    path('bio/', user_form, name='user-form'),
    path('upload/', handle_file_upload, name='file-upload'),
]

mysite/shopapp/urls.py
from django.urls import path
from .views import (
    ShopIndexView,
    GroupsListView,
    ProductsListView,
    ProductDetailsView,
    OrdersListView,
    ProductCreateView,
    OrderDetailView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = 'shopapp'

urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='products_details'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archived/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details'),
]

mysite/myauth/models.py
from django.db import models

# Create your models here.

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + '...'

    def __str__(self) -> str:
        return f'Product(pk={self.pk}, name={self.name})'


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

mysite/requestdataapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import InMemoryUploadedFile


class UserBioForms(forms.Form):
    name = forms.CharField(max_length=100)
    age = forms.IntegerField(label='Your age', min_value=1, max_value=120)
    bio = forms.CharField(label='Biography', widget=forms.Textarea)


def validate_file_name(file: InMemoryUploadedFile) -> None:
    if file.name and 'virus' in file.name:
        raise ValidationError('file name should not contain "virus"')


class UploadFileForm(forms.Form):
    file = forms.FileField(validators=[validate_file_name])

mysite/shopapp/forms.py
from django import forms
from django.contrib.auth.models import Group

from .models import Product


# class ProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = 'name', 'price', 'description', 'discount'


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

mysite/myauth/views.py
# from django.contrib.auth import login, authenticate
# from django.http import HttpRequest
# from django.shortcuts import render, redirect
#
#
# def login_view(request: HttpRequest):
#     if request.method == 'GET':
#         if request.user.is_authenticated:
#             return redirect('/admin/')
#
#         return render(request, 'myauth/login.html')
#
#     username = request.POST['username']
#     password = request.POST['password']
#
#     user = authenticate(request, username=username, password=password)
#
#     if user is not None:
#         login(request, user)
#         return redirect('/admin/')
#     return render(request, 'myauth/login.html', {'error': 'Invalid login credentials'})

mysite/requestdataapp/views.py
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render

from .forms import UserBioForms, UploadFileForm


def process_get_view(request: HttpRequest) -> HttpResponse:
    a = request.GET.get('a', '')
    b = request.GET.get('b', '')
    result = a + b
    context = {
        'a': a,
        'b': b,
        'result': result,
    }
    return render(request, 'requestdataapp/request-query-params.html', context=context)


def user_form(request: HttpRequest) -> HttpResponse:
    context = {
        'form': UserBioForms(),
    }
    return render(request, 'requestdataapp/user-bio-form.html', context=context)


def handle_file_upload(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            myfile = form.cleaned_data['file']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            print('Saved file', filename)
    else:
        form = UploadFileForm()
    context = {
        'form': form
    }
    return render(request, 'requestdataapp/file-upload.html', context=context)

mysite/shopapp/views.py
from timeit import default_timer
from django.contrib.auth.models import Group
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from shopapp.models import Product, Order
from .forms import GroupForm


class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphon', 999),
        ]
        context = {
            'time_running': default_timer(),
            'products': products,
        }
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            'form': GroupForm(),
            'groups': Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    queryset = Product.objects.filter(archived=False)
    context_object_name = 'products'


class ProductDetailsView(DetailView):
    template_name = 'shopapp/products-details.html'
    model = Product
    context_object_name = 'product'


class ProductCreateView(CreateView):
    model = Product
    fields = 'name', 'price', 'description', 'discount'
    success_url = reverse_lazy('shopapp:products_list')


class ProductUpdateView(UpdateView):
    model = Product
    fields = 'name', 'price', 'description', 'discount'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse('shopapp:products_details', kwargs={'pk': self.object.pk},)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(ListView):
    queryset = (
        Order.objects
        .select_related('user')
        .prefetch_related('products')
    )


class OrderDetailView(DetailView):
    queryset = (
        Order.objects
        .select_related('user')
        .prefetch_related('products')
    )

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

mysite/requestdataapp/templates/requestdataapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
    {% block body %}

    {% endblock %}

    <br>
    <div>
        HTTP User-Agent {{ request.user_agent }}
    </div>
</body>
</html>

mysite/requestdataapp/templates/requestdataapp/file-upload.html
{% extends 'requestdataapp/base.html' %}

{% block title %}
    File upload
{% endblock %}

{% block body %}
    <h1>Upload file</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
{% endblock %}

mysite/requestdataapp/templates/requestdataapp/request-query-params.html
{% extends  'requestdataapp/base.html' %}

{% block title %}
    Demo request params
{% endblock %}

{% block body %}
    <h1>Good afternoon, {% firstof request.GET.name 'User' %}</h1>
    <div>
        <pre>
            a = '{{ a }}'
            b = '{{ b }}'
            result = '{{ result }}'
        </pre>
    </div>
{% endblock %}

mysite/requestdataapp/templates/requestdataapp/user-bio-form.html
{% extends 'requestdataapp/base.html'%}

{% block title %}
  User BIO
{% endblock %}

{% block body %}
  <h1>User form</h1>
  <div>
    <form  method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">
        Submit
      </button>
    </form>
  </div>
  {% if request.POST %}
    <div>
      <h2>Previous form data:</h2>
      <table>
        <tr>
          <td>Full name:</td>
          <td>{{ request.POST.name }}</td>
        </tr>

        <tr>
          <td>Age:</td>
          <td>{{ request.POST.age }}</td>
        </tr>

        <tr>
          <td>Bio:</td>
          <td>
            <p> {{request.POST.bio|linebreaks }}</p>
          </td>
        </tr>
      </table>
    </div>
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base body
    {% endblock %}
    <div>
        {% now 'H:i' %}
    </div>
    <div>
        {% now 'l' as current_weekday %}
        Today is {{ current_weekday }}
    </div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create a new product</h1>
  <div>
    <form method="post">
      {% csrf_token %}

      {{ form.as_p }}

      <button type="submit">
        Create
      </button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}"
       >Back to products list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        {% if not groups %}
            <h3>No groups yet</h3>
        {% else %}
            <ul>
                {% for group in groups %}
                <li>
                    <div>{{ group.name }}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                        <li>
                            {{ permission.name }}
                            (<code>{{ permission.codename }}</code>)
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Order #{{ object.pk }}</h1>
  <div>
    <p>Order by {% firstof object.user.first_name object.user.username %}</p>
    <p>Promocode: <code>{{ object.promocode }}</code></p>
    <p>Delivery address: {{object.delivery_address }}</p>
    <div>
      Product in order:
      <ul>
        {% for product in object.products.all %}
          <li>{{ product.name }} for ${{ product.price }}</li>
        {% endfor %}
      </ul>
     </div>
  </div>
  <div>
    <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends  'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
                <div>
                    <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details #{{ order.pk }}</a></p>
                    <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                    <p>Promocode: <code>{{ order.promocode }}</code></p>
                    <p>Delivery address: {{order.delivery_address }}</p>
                    <div>
                        Product in order:
                        <ul>
                            {% for product in order.products.all %}
                                <li>{{ product.name }} for ${{ product.price }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/orders-list.html
{% extends  'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if orders %}
        <div>
            {% for order in orders %}
                <div>
                    <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                    <p>Promocode: <code>{{ order.promocode }}</code></p>
                    <p>Delivery address: {{order.delivery_address }}</p>
                    <div>
                        Product in order:
                        <ul>
                            {% for product in order.products.all %}
                                <li>{{ product.name }} for ${{ product.price }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm archived {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to archived {{ object.name }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:products_details' pk=object.pk %}">Back to product</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Archived</button>
    </form>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create product</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}"
       >Back to products list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1>Update product</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:products_details' pk=object.pk %}"
    >Back to product #{{ object.pk }}</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product #{{ product.pk }}
{% endblock %}

{% block body %}
  <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
      <div>Description: <em>{{ product.description }}</em></div>
      <div>Price: {{ product.price }}</div>
      <div>Discount: {{ product.discount }}</div>
      <div>Archived: {{ product.archived }}</div>
    </div>
  <div>
    <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archived product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products list
{% endblock %}

{% block body %}
    <h1>Products:</h1>
    {% if products %}
        <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url 'shopapp:products_details' pk=product.pk %}">Name: {{ product.name }}</a></p>
                    <p>Price: {{ product.price }}</p>
                    <p>Discount: {% firstof product.discount 'no discount' %}</p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No product yet</h3>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:product_create' %}"
           >Create a new product</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>Hello Shop Index!</h1>
    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name }}({{ name|length }}) for ${{ price }}</li>
                {% if name|length == 7 %}
                    <snap>Lucky product!</snap>
                {% endif %}
            {% empty %}
                No product here
            {% endfor %}
        </ul>
    </div>
    <div>
        Time running: {{ time_running }}
    </div>
    <div>
        {% lorem 3 p random %}
    </div>
{% endblock %}